### PR TITLE
integration specs for views and fix n+1 problems

### PR DESCRIPTION
**Pull request by camilevahviraki**
### **In this project we did the following:**

- Solve sure that the N+1 problem 

-  Use Capybara to write integration tests for each view
  
    - User index page
 
    - user show page

    - User post index page

    - Post show page

### CODE REVIEW

**Review by rloterh — CHANGES_REQUESTED** [review]
Hi Camile, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has needs the following corrections before review:
- [ ] There is a mismatch in database record field, and hence, an error is thrown in attempt to migrate the database during setup process. Kindly ensure to fix this issue. I also suggest that your default database adapter for this project should be set to `postgresql`

- [ ] Also, kindly ensure that your ReadMe is detailed and follows this [recommended microverse template](https://github.com/microverseinc/readme-template/blob/master/README.md); Add instructions on how run test cases for your project, and provide a description for the intro section.

**Database Migration error:**
image



Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by dasileker — CHANGES_REQUESTED** [review]
### **Hi @camilevahviraki,** 

### **Good job so far!**
There are some issues that you still need to work on to go to the next project but you are almost there!

## **Highlights**
- Linters are green ✅.
- The readme file is good✅.
- PR is well made ✅.

## Required Changes ♻️
_Check the comments under the review._

- Hello and nice work on adding the test but there are some of them fail, please take a look at the screenshots, a lot of them are syntax errors review your Controller folder.

Capture d’écran 2022-08-24 175332
Capture d’écran 2022-08-24 175349
Capture d’écran 2022-08-24 175408
 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by camilevahviraki** [comment]
Hi @dasileker , All tests are working fine in my computer.
Maybe there is a gem that you forgot to install

Here is the screenshot:
Screenshot from 2022-08-24 19-44-52

Thank you for answering me

**Comment by dasileker** [comment]
Hello,  the gem are already installed in your app so I  don't think so,  but maybe it's an issue  on my end please  re-submit if you want maybe the next reviewer will not have any problems .

**Comment by camilevahviraki** [comment]
Thank you @dasileker

**Review by aimemalaika — APPROVED** [review]
Hi @camilevahviraki , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉

- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️
- PR has a good title and summary. ✔️

133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
