### PR TITLE
Add api endpoint

### PR DESCRIPTION
**Pull request by camilevahviraki**
### **In this branch we did the following:**

-   Create an API endpoint to list all posts for a user.
-  Create an API endpoint to list all comments for a user's post.
-  Create an API endpoint to add a comment to a post. 
-   Add authentication to your API endpoints.

### CODE REVIEW

**Review by rloterh — CHANGES_REQUESTED** [review]
Hi Camile & Ogaga, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has needs the following correction before review:
- [ ] There is a mismatch in database record field, and hence, an error is thrown in attempt to migrate the database during setup process. Kindly ensure to fix this issue.

**Database Migration error:**
image



Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by camilevahviraki** [comment]
Hi @rloterh ,
That is not an error, 

You have just to write
- `rails db:drop:all`
- `bin/rails db:environment:set RAILS_ENV=development`
-  `rails db:reset`
- rails `db:migrate`

**Review by Mihndim2020 — APPROVED** [review]
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
### Hi Team, 

### Good job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Descriptive Readme file
:heavy_check_mark: Clean/Organized  code

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

Congratulations-Memes-FEATURED

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can get to me on slack  using this handle @mihndim.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by camilevahviraki** [comment]
Thank you Mihndim2020

**Pull request merged**
